### ISSUE TITLE
As a developert I want to monitor the a22 data entering the db, so I can intervene swiftly if some error occurs

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/A22TrafficConnector#4]
Following Chris M. suggestions we would like to monitor a22 data.
```
Ciao,

segretemente ho monitorato il lag del a22 traffic connector durante gli ultimi giorni
(vedi grafico).

La query semplicemente da now e now - max(timestamp nel db):

select extract(epoch from now()), extract(epoch from (now() - to_timestamp(max(timestamp)))) from a22.a22_traffic

Come vedi c'e` stato un evento il 29 dove il lag schizzava a 1 quasi un'ora, altrimenti va sempre bene.

Non penso sia importante capire cos'e` successo il 29. Forse Beanstalk ha ricreata l'instanza oppure
l'A22 ha rebootato il server o cosa mai. L'importante e` che sia rientrato automaticamente.

IMHO quello che andrebbe fatto e` semplicemente prendere questa query e` aggiungerla a 
qualche monitoring. Nella stanza di Peter e Patrick B. vedo questi monitor sopra l'armadio. Penso ci
sia qualcosa gia` in place per fare questo tipo di operazione?

Cosi`, se p.e. sappiamo che ogni tanto un'ora di lag succede ed e` recuperabile, la soglia d'allarme
potrebbe essere messa a 6 ore?

```

**Comment by bertolla** [comment]
@ohnewein 
I noticed this only now because nobody was assigned.
I guess this is for me?

**Comment by ohnewein** [comment]
Hi @bertolla I do not remember. I think someone during the last Sprint meeting asked me to put it into the "Spint To Do" lane. Not sure if it was @Piiit or @rcavaliere ...

**Comment by rcavaliere** [comment]
@bertolla @ohnewein yes it is for you Patrick B., it is related to the work related to the monitoring you are doing and that you already told me.

**Comment by bertolla** [comment]
Some monitoring I already have done in this form where you can see latest data which is not getting updated anymore: https://github.com/noi-techpark/issues/blob/master/missingData.md

**Comment by bertolla** [comment]
I think with this steps I covered the request:
- created user in a22db called grafana
- granted right permissions
- created a new Dashboard
- used Chrisquery to display the seconds since when the last update took place using a Gauge chart.
To test it, login with your grafana account, check dashboards and find `a22 current state` where you will see it.
The data is up to date if you refresh it you will get the latest data or you can also set automatic refresh interval.

**Comment by rcavaliere** [comment]
Wonderful! To test this, I would need a grafana account (I don't have one). Can you prepare this for me! Thanks

**Comment by rcavaliere** [comment]
Tested. This is a very nice MVP. Let's close this issue and organize together the next steps (I will make a suggestion for a new user story).
